Squashed commit of the following:
commit 3b97af0dde880fdde865a4490da23ba81f7da4cd
Author: Aidan Garske <aidan@wolfssl.com>
Date:   Thu Sep 11 11:09:23 2025 -0700

    Add better failure detection

commit d6cfd4c312241b035924c8d8a9dd859e4953d799
Author: Aidan Garske <aidan@wolfssl.com>
Date:   Thu Sep 11 10:17:24 2025 -0700

    Add DRY install and fix bug

commit 82a6c82d3368a7e15502e22309d877aef847b1d6
Author: Aidan Garske <aidan@wolfssl.com>
Date:   Thu Sep 11 09:43:02 2025 -0700

    Add correct exit handling

commit ab74618a50513a0c2b4b94dc9c04c7d6bc48d390
Author: Aidan Garske <aidan@wolfssl.com>
Date:   Wed Sep 10 18:12:06 2025 -0700

    Update debug to work correctly

commit a3c82ea5c23ad56a6347e68ba3581063f35e05b8
Author: Aidan Garske <aidan@wolfssl.com>
Date:   Wed Sep 10 18:04:00 2025 -0700

    Add debug to figure out ret

commit 741ba834e3d479e222582ffdd105b600a20621a5
Author: Aidan Garske <aidan@wolfssl.com>
Date:   Wed Sep 10 17:35:59 2025 -0700

    Dont do the source env

commit 162ecbc6bcde14265d39cd5b1ea56f4a351cc844
Author: Aidan Garske <aidan@wolfssl.com>
Date:   Wed Sep 10 17:24:33 2025 -0700

    Install in correct order

commit 13d014e00b1b285a6c0e8c4138ba707fbf3a6e47
Author: Aidan Garske <aidan@wolfssl.com>
Date:   Wed Sep 10 17:16:24 2025 -0700

    Add _dev as well for ossl

commit c130172995a5d60b82b8149d23b8c8fd71da2a18
Author: Aidan Garske <aidan@wolfssl.com>
Date:   Wed Sep 10 17:00:16 2025 -0700

    Add debug and dont specify the ossl install

commit 4354399a464e6cb7bfcf4be60b3c91427a38c40b
Author: Aidan Garske <aidan@wolfssl.com>
Date:   Wed Sep 10 16:35:53 2025 -0700

    Add only the main wp package

commit bc64e270c41b0529e868c1b7cd073e28e7e37bee
Author: Aidan Garske <aidan@wolfssl.com>
Date:   Wed Sep 10 16:09:07 2025 -0700

    Add correct syntax to find package

commit f3fdc430ff8d202c7be9d40564ee8c8e994a4fd4
Author: Aidan Garske <aidan@wolfssl.com>
Date:   Wed Sep 10 15:46:44 2025 -0700

    Add distinct commit hash

commit 808c4f89c2beab9d0e1965c4468b2f1156a2186b
Author: Aidan Garske <aidan@wolfssl.com>
Date:   Wed Sep 10 13:19:25 2025 -0700

    Only test 5.8.2

commit 08ac4d71941c3ec7e1366d4145cf7da5a18a8a3d
Author: Aidan Garske <aidan@wolfssl.com>
Date:   Wed Sep 10 12:42:48 2025 -0700

    Add comment out

commit 9e26b93fce2b6c7322aa0987125dbcfb07147138
Author: Aidan Garske <aidan@wolfssl.com>
Date:   Wed Sep 10 12:31:41 2025 -0700

    Add .deb support for Github Workflows

diff --git a/.github/workflows/debian-package.yml b/.github/workflows/debian-package.yml
--- a/.github/workflows/debian-package.yml
+++ b/.github/workflows/debian-package.yml
@@ -60,29 +60,37 @@ jobs:
         # List all tags
         git tag -l
 
-    - name: Install wolfssl debian package
-      run: |
-        mkdir -p "/tmp/wolfssl-pkg"
-        cd "/tmp/wolfssl-pkg"
-        
-        # Install wolfssl packages
-        chmod +x $GITHUB_WORKSPACE/debian/install-wolfssl.sh
-        $GITHUB_WORKSPACE/debian/install-wolfssl.sh \
-          $GITHUB_WORKSPACE/.github/packages/debian-wolfssl.tar.gz \
-          "/tmp/wolfssl-pkg"
+    - name: Download wolfSSL packages
+      uses: actions/download-artifact@v4
+      with:
+        name: wolfssl-debian-packages-${{ github.sha }}
+        path: /tmp/wolfssl-artifacts
 
-        # Create wolfprov-packages directory and move wolfssl files there
+    - name: Download OpenSSL/wolfProvider packages
+      uses: actions/download-artifact@v4
+      with:
+        name: openssl-wolfprov-debian-packages-${{ github.sha }}
+        path: /tmp/openssl-wolfprov-artifacts
+
+    - name: Install wolfSSL debian packages from artifact
+      run: |
+        set -e
+        echo "WolfSSL artifacts:"
+        ls -la /tmp/wolfssl-artifacts || true
+
+        # Install wolfSSL runtime and headers (from our artifact, not apt)
+        wolfssl_debs=$(ls -1 /tmp/wolfssl-artifacts/*.deb 2>/dev/null || true)
+        if [ -n "$wolfssl_debs" ]; then
+          echo "Installing wolfSSL packages: $wolfssl_debs"
+          apt install -y $wolfssl_debs
+        else
+          echo "ERROR: No wolfSSL .deb files found in artifact"
+          exit 1
+        fi
+
+        # Copy wolfSSL debs into the unified artifacts directory for later upload
         mkdir -p "/tmp/wolfprov-packages"
-        echo "Moving wolfssl files to artifacts directory..."
-        
-        # Copy all wolfssl-related files (source and binary packages)
-        find /tmp/wolfssl-pkg -name "*wolfssl*" -type f -name "*.deb" -exec cp {} /tmp/wolfprov-packages/ \;
-        find /tmp/wolfssl-pkg -name "*wolfssl*" -type f -name "*.dsc" -exec cp {} /tmp/wolfprov-packages/ \;
-        find /tmp/wolfssl-pkg -name "*wolfssl*" -type f -name "*.tar.gz" -exec cp {} /tmp/wolfprov-packages/ \;
-        find /tmp/wolfssl-pkg -name "*wolfssl*" -type f -name "*.orig.tar.gz" -exec cp {} /tmp/wolfprov-packages/ \;
-        
-        echo "WolfSSL files in artifacts directory:"
-        ls -la /tmp/wolfprov-packages/*wolfssl* || true
+        cp -v /tmp/wolfssl-artifacts/*.deb /tmp/wolfprov-packages/ 2>/dev/null || true
 
     - name: Build Debian package
       run: |
@@ -205,7 +213,11 @@ jobs:
       if: always()
       uses: actions/upload-artifact@v4
       with:
+<<<<<<< HEAD
         name: wolfprovider-debian-packages${{ matrix.debug_flag }}
+=======
+        name: debian-package-test-artifacts-${{ github.sha }}
+>>>>>>> 92bcce9 (Squashed commit of the following:)
         path: |
           /tmp/wolfprov-packages/*.deb
           /tmp/wolfprov-packages/*.dsc
@@ -223,7 +235,7 @@ jobs:
     - name: Download artifacts from previous job
       uses: actions/download-artifact@v4
       with:
-        name: wolfprovider-debian-packages
+        name: debian-package-test-artifacts-${{ github.sha }}
         path: /tmp/artifacts
   
     - name: Set up environment
